config/routes.rb
Stripe::Application.routes.draw do
  resources :customers

  resources :charges

end

app/models/charge.rb
class Charge < ActiveRecord::Base
  attr_accessible :amount, :amount_refunded, :currency, :description, :disputed, :failure_message, :fee, :invoice, :livemode, :object, :paid, :refunded, :stripe_id
  
  validates :amount, :numericality => { :greater_than_or_equal_to  => 0 }
  validates :fee, :numericality => { :greater_than_or_equal_to  => 0 }
  validates :amount_refunded, :numericality => { :greater_than_or_equal_to  => 0, :allow_nil => true }
  validates :currency, :length => {:is => 3}
  
  belongs_to :customer
  
  scope :successful, where(:paid => true)
  scope :failed, where("paid = ? and failure_message is not null", false )
  scope :disputed, where(:disputed => true)
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :firstname, :lastname
  
  validates :firstname, :presence => true
  validates :lastname, :presence => true
  
  has_many :charges
  
  def name
    [firstname, lastname].reject(&:blank?).join(" ")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # GET /charges
  # GET /charges.json
  def index
    @successful_charges = Charge.successful
    @disputed_charges   = Charge.disputed
    @failed_charges     = Charge.failed

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @charges }
    end
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @charge = Charge.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/new
  # GET /charges/new.json
  def new
    @charge = Charge.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @charge }
    end
  end

  # GET /charges/1/edit
  def edit
    @charge = Charge.find(params[:id])
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(params[:charge])

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render json: @charge, status: :created, location: @charge }
      else
        format.html { render action: "new" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /charges/1
  # PUT /charges/1.json
  def update
    @charge = Charge.find(params[:id])

    respond_to do |format|
      if @charge.update_attributes(params[:charge])
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy

    respond_to do |format|
      format.html { redirect_to charges_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stripe_id %><br />
    <%= f.text_field :stripe_id %>
  </div>
  <div class="field">
    <%= f.label :object %><br />
    <%= f.text_field :object %>
  </div>
  <div class="field">
    <%= f.label :livemode %><br />
    <%= f.check_box :livemode %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :disputed %><br />
    <%= f.check_box :disputed %>
  </div>
  <div class="field">
    <%= f.label :fee %><br />
    <%= f.number_field :fee %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :refunded %><br />
    <%= f.check_box :refunded %>
  </div>
  <div class="field">
    <%= f.label :amount_refunded %><br />
    <%= f.number_field :amount_refunded %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :failure_message %><br />
    <%= f.text_field :failure_message %>
  </div>
  <div class="field">
    <%= f.label :invoice %><br />
    <%= f.text_field :invoice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.haml
.failed
  %h1 Failed charges
  %table
    %tr
      %th Customer Name
      %th Amount
      %th Failed At
    - @failed_charges.each do |charge|
      %tr.item
        %td= charge.customer.try(:name)
        %td= number_to_currency(charge.amount, :unit => charge.currency)
        %td= charge.created_at
%br/

.disputed
  %h1 Disputed charges
  %table
    %tr
      %th Customer Name
      %th Amount
      %th Disputed At
    - @disputed_charges.each do |charge|
      %tr.item
        %td= charge.customer.try(:name)
        %td= number_to_currency(charge.amount, :unit => charge.currency)
        %td= charge.created_at
 
.successful        
  %h1 Successful charges
  %table
    %tr
      %th Customer Name
      %th Amount
      %th Successful At
    - @successful_charges.each do |charge|
      %tr.item
        %td= charge.customer.try(:name)
        %td= number_to_currency(charge.amount, :unit => charge.currency)
        %td= charge.created_at

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stripe:</b>
  <%= @charge.stripe_id %>
</p>

<p>
  <b>Object:</b>
  <%= @charge.object %>
</p>

<p>
  <b>Livemode:</b>
  <%= @charge.livemode %>
</p>

<p>
  <b>Amount:</b>
  <%= @charge.amount %>
</p>

<p>
  <b>Currency:</b>
  <%= @charge.currency %>
</p>

<p>
  <b>Disputed:</b>
  <%= @charge.disputed %>
</p>

<p>
  <b>Fee:</b>
  <%= @charge.fee %>
</p>

<p>
  <b>Paid:</b>
  <%= @charge.paid %>
</p>

<p>
  <b>Refunded:</b>
  <%= @charge.refunded %>
</p>

<p>
  <b>Amount refunded:</b>
  <%= @charge.amount_refunded %>
</p>

<p>
  <b>Description:</b>
  <%= @charge.description %>
</p>

<p>
  <b>Failure message:</b>
  <%= @charge.failure_message %>
</p>

<p>
  <b>Invoice:</b>
  <%= @charge.invoice %>
</p>


<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.firstname %></td>
    <td><%= customer.lastname %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @customer.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @customer.lastname %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stripe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>